spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.astondevs.kafkastartermvn.deserializer.CustomDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: ru.astondevs.kafkastartermvn.deserializer.CustomDeserializer
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    hikari:
      maximum-pool-size: ${max_pool_size:2}

    # Настройки для миграции БД
  liquibase:
    default-schema: public
    change-log: classpath:/changelog/changelog-cumulative.xml
    user: ${datasource_username}
    password: ${datasource_password}
    enabled: ${liquibase_enable:false}

# Настройки логирования
logging:
  level:
    ROOT: ${log_root_level:DEBUG}
ru:
  astondevs:
    app:
      kafka:
        topic: test
        type: ru.astondevs.orderservice.kafka.dto.RestaurantValidateDto